sayi1=input("yaşınızı Giriniz: ")
print(sayi1)
print("Demek",sayi1,"yaşındasınız.")
print(type(sayi1))
print(sayi1*6)
sayi1=int(input("yaşınızı Giriniz: "))
print(sayi1*6)
sayi1=float(input("yaşınızı Giriniz: "))
print(sayi1*6)